Tout Fichier :: Correction syntaxique.
Grainus/RedSquareGame pull request #17
Opened 2022-10-31 20:45 UTC by WyllasSidjeno

Correction du code afin de mieux refler les meilleur pratique, et surtout, le PEP-8.

2022-10-31 20:57 UTC, Grainus commented
Indentation à 1 ou 2 niveaux de plus plutôt que suivant la parenthèse est plus facile à lire.

2022-10-31 21:29 UTC, Grainus requested changes
Overall correcte, mais beaucoup de points douteux. PEP 8 accepte plusieurs styles pour les  [lignes de continuation](https://peps.python.org/pep-0008/#indentation) et le deuxième montré était déjà utilisé dans le projet.

2022-10-31 21:29 UTC, Grainus commented on controller.py
> +        import c31Geometry.c31Geometry2 as Geo  # type: ignore                 #
```suggestion
        ############################### TESTING ###############################
        import c31Geometry.c31Geometry2 as geo  # type: ignore                 #
```

2022-10-31 21:29 UTC, Grainus commented on controller.py
> +            canvas, Geo.Point(100, 100), 75, 150, "blue", Geo.Vecteur(1, 1)   #
```suggestion
            canvas, geo.Point(100, 100), 75, 150, "blue", geo.Vecteur(1, 1)   #
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +import c31Geometry.c31Geometry2 as Geo  # type: ignore
```suggestion
import c31Geometry.c31Geometry2 as geo  # type: ignore
```
Les modules ne doivent pas avoir de majuscule (ex: `import tkinter as tk`)

2022-10-31 21:29 UTC, Grainus commented on model.py
> +                 ):
```suggestion
            pos: geo.Point,
            width: float,
            height: float,
            color: str,
        ):
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +        halfsize = Geo.Vecteur(width, height) / 2
```suggestion
        halfsize = geo.Vecteur(width, height) / 2
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +        self.p1, self.p2 = Geo.Point(*coords[:2]), Geo.Point(*coords[2:])
```suggestion
        self.p1, self.p2 = geo.Point(*coords[:2]), geo.Point(*coords[2:])
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +                 ):
```suggestion
            pos: geo.Point,
            width: float,
            height: float,
            color: str,
            speed: Geo.Vecteur,
        ):
```

2022-10-31 21:29 UTC, Grainus commented on controller.py
> +                             self.on_options, self.on_highscores)
```suggestion
        self.view = MenuView(
                root, self.new_game, self.on_quit,
                self.on_options, self.on_highscores
        )
```

2022-10-31 21:29 UTC, Grainus commented on controller.py
> +        playersize = 50
Ces variables sont temporaires de toute façon

2022-10-31 21:29 UTC, Grainus commented on model.py
> +                 ):
```suggestion
            border: float,
            width: float,
            height: float,
            color: str,
            enemy: Enemy  # TESTING
        ):
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +            # pos: Position du centre de l'objet. <- TODO: à supprimer ?
Les commentaires dans les strings sont affichés dans la string...
L'argument permet de configurer la position initiale, qu'on pourrait changer dans les options.

2022-10-31 21:29 UTC, Grainus commented on model.py
> +        pos = Geo.Point(cwidth / 2, cheight / 2)
```suggestion
        pos = geo.Point(cwidth / 2, cheight / 2)
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +            )
```suggestion
        )
```

2022-10-31 21:29 UTC, Grainus commented on model.py
> +                )
```suggestion
                event.x - self.width/2,
                event.y - self.height/2
            )
```
Les opérateurs avec une plus grande priorité sont groupés sans espaces

2022-10-31 21:29 UTC, Grainus commented on view.py
> +                                  y=self.logo_height+self.btn_height)
```suggestion
        self.btn_quit.place(
                x=(450-self.btn_width) / 2,
                y=self.logo_height + (self.btn_height*2)
        )
        self.btn_options.place(
                x=(450 - (self.btn_width*2)) / 2,
                y=self.logo_height+self.btn_height
        )
        self.btn_highscores.place(
                x=(450 - (self.btn_width*2)) / 2 + self.btn_width,
                y=self.logo_height+self.btn_height
        )
```
Ce code donne l'impression qu'on descend en indentation.

2022-10-31 21:31 UTC, Grainus commented
@WyllasSidjeno Utilise les [batch de suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) pour ne pas créer une tonne de commits.

2022-10-31 21:57 UTC, WyllasSidjeno commented on model.py
> +                 ):
Selon moi, beaucoup moins optimal à la lecture et agréable, mais je m'en fous.

Raison de mon raisonnement : Plus facile à la lecture, surtout si une fonction ou une autre variable est juste après

2022-10-31 22:00 UTC, WyllasSidjeno commented on model.py
> +            # pos: Position du centre de l'objet. <- TODO: à supprimer ?
Sauf qu'elle s'affiche comme étant dans le constructeur de player, et non pas comme étant membre de player.

Tout les autres elements sont membres du constructeur, sauf celui-ci. Pourquoi ? Aucun string ne l'explique.

2022-10-31 22:07 UTC, Grainus commented on model.py
> +            # pos: Position du centre de l'objet. <- TODO: à supprimer ?
Correcte, la variable est documentée mais pas présente dans le code. Je comprends mieux ce que tu veux dire.

2022-10-31 22:09 UTC, Grainus commented on model.py
> +            # pos: Position du centre de l'objet. <- TODO: à supprimer ?
Je proposerait d'ajouter pos (et probablement les autres valeurs) comme optionnelles et les calculer selon config si nécessaire

2022-11-01 02:05 UTC, WyllasSidjeno commented
Je crois avoir tout fixe. Hésite pas à relancer au besoin si jai oublié un point ou deux. Je suis pas très agile avec Git.

2022-11-01 14:24 UTC, AsadPug reviewed
pep 8 is op

2022-11-01 14:24 UTC, AsadPug commented on model.py
> +                 ):
yea c'est mieux ça que la solution au dessus

2022-11-01 14:24 UTC, AsadPug approved these changes
I aprove 💯

2022-11-01 14:36 UTC, Grainus requested changes
Juste 3 erreurs de ma part, j'accepte tout de suite après

2022-11-01 14:36 UTC, Grainus commented on model.py
> +        ):
```suggestion
    ):
```

2022-11-01 14:36 UTC, Grainus commented on model.py
> +        ):
```suggestion
    ):
```

2022-11-01 14:36 UTC, Grainus commented on model.py
> +        ):
```suggestion
    ):
```

2022-11-01 15:02 UTC, Grainus approved these changes
Tout semble en ordre.

2022-11-01 15:04 UTC, AsadPug approved these changes
I reaprove 💯

2022-11-01 15:05 UTC, merged