Vue
Grainus/RedSquareGame pull request #35
Opened 2022-11-04 06:21 UTC by AsadPug

Pull request pour rajouter options controller et options view à dev. 

Highscore view et highscore controller ainsi que game end controller et game end view n'est pas updated donc ne pas merge cette partie.

Seulement merge pour le menu d'option

2022-11-05 03:41 UTC, Grainus requested changes
On envoie pas highscores.db en production.
Sinon, ***PLEASE*** utilise les batch de suggestion, approve pas 17 commits un à la fois sinon je vais paniquer.

2022-11-05 03:41 UTC, Grainus commented on controller.py
>          )
```suggestion
        )

```

2022-11-05 03:41 UTC, Grainus commented on controller.py
> +
```suggestion
```

2022-11-05 03:41 UTC, Grainus commented on controller.py
> +        self.frame.pack_forget()
Comme on crée un nouveau controller et vue à chaque fois, ne serait-il pas mieux d'utiliser destroy?

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        self.btn_width = 200
```suggestion
        self.btn_height = size["Height"] / 4,5
        self.btn_width = 2 * self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
>          self.nameEntry.place(x=150, y=120)
```suggestion
        self.nameEntry.place(relx=1/3, rely=1/3.75)
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        self.btn_width = 200
```suggestion
        self.btn_height = size["Height"] / 4,5
        self.btn_width = 2 * self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450 - self.btn_height
```suggestion
            x=(size["Width"] - (self.btn_width*2)) / 2,
            y=size["Height"] - self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450 - self.btn_height
```suggestion
            x=(size["Width"] - (self.btn_width*2)) / 2 + self.btn_width,
            y=size["Height"] - self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        self.diff_width = 100
```suggestion
        size = Config.get_instance()["Game"]["Size"]
        self.on_quit = on_quit
        self.on_menu = on_menu
        self.options_canvas = tk.Canvas(self.frame, width=size["Width"], height=size["Height"])
        self.options_canvas.pack()
        self.options_canvas.create_text(225, 35, text="Options", font=("Arial", 50))

        # Dimensions des widgets
        self.btn_height = size["Height"] / 4.5
        self.btn_width = self.btn_height * 2
        self.diff_height = self.btn_height / 2
        self.diff_width = self.diff_height * 2
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +                config["Game"]["Difficulty"]["Level"] = str(diff)
```suggestion
                config["Game"]["Difficulty"]["Level"] = diff.name
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450 - self.btn_height
```suggestion
            x=(size["Width"] - (self.btn_width*2)) / 2,
            y=size["Height"] - self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450 - self.btn_height
```suggestion
            x=(size["Width"] - (self.btn_width*2)) / 2 + self.btn_width,
            y=size["Height"] - self.btn_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450/2 - (self.diff_height*2)
```suggestion
            x=(size["Width"] - self.diff_width) / 2,
            y=size["Height"]/2 - (self.diff_height*2)
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +            y=450/2 - self.diff_height
```suggestion
            x=(size["Width] - self.diff_width) / 2,
            y=size["Height"]/2 - self.diff_height
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        self.btn_hard.place(x=(450 - self.diff_width) / 2,y=450/2)
```suggestion
        self.btn_hard.place(
            x=(size["Width"] - self.diff_width) / 2,
            y=size["Height"]/2
        )
```

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        )
You know the drill, utilise le module config

2022-11-05 03:41 UTC, Grainus commented on view.py
> +        self.pack()
```suggestion
        self.pack()

```

Newline à la fin nécessaire pour les git diffs

2022-11-05 03:44 UTC, Grainus commented
> Highscore view et highscore controller ainsi que game end controller et game end view n'est pas updated donc ne pas merge cette partie.
> 
> Seulement merge pour le menu d'option

On ne peut pas faire des merge à moitié...

2022-11-06 19:15 UTC, AsadPug reviewed
Aprove change from hardcoding 450 to config

2022-11-06 19:15 UTC, AsadPug commented on controller.py
> +        self.frame.pack_forget()
yea effectivement

2022-11-07 17:23 UTC, Grainus requested changes

2022-11-07 17:23 UTC, Grainus commented on view.py
> +        self.btn_width = 200
```suggestion
        self.btn_height = size["Height"] / 4.5
        self.btn_width = self.btn_height * 2
```

2022-11-07 17:23 UTC, Grainus commented on view.py
> +            y=450-self.btn_height
```suggestion
            x=(size["Width"]- (self.btn_width*2)) / 2,
            y=size["Height"]-self.btn_height
        )
        self.btn_quit.place(
            x=(size["Width"]- (self.btn_width*2)) / 2 + self.btn_width,
            y=size["Height"]-self.btn_height
```

2022-11-07 17:25 UTC, Grainus requested changes

2022-11-07 17:25 UTC, Grainus commented on controller.py
> +        self.frame.pack_forget()
```suggestion
        self.frame.destroy()
```

2022-11-07 17:58 UTC, Grainus commented
@WyllasSidjeno review please

2022-11-09 22:18 UTC, WyllasSidjeno approved these changes

2022-11-10 18:40 UTC, merged